version: "3.3"

services:
  web:
    image: nginx:alpine
    container_name: web
    hostname: web
    ports:
      - 80:80
    depends_on:
      - phpfpm
    volumes:
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/proyectos/personal/php/perrot/:/var/www/html

  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfiles/php/Dockerfile
    container_name: phpfpm
    hostname: phpfpm
    restart: always
    environment:
      DOCKER_USER: www-data
      DOCKER_GROUP: www-data
      REQUEST_TIMEOUT: 60
      MAX_INPUT_TIME: 60
      POST_MAX_SIZE: 30M
    depends_on:
      - database
      - redis
    volumes:
      - ~/proyectos/personal/php/perrot/:/var/www/html
      - ./etc/infrastructure/php/conf.d/loaded.ini:/usr/local/etc/php/conf.d/loaded.ini

  database:
    image: mariadb:latest
    container_name: database
    hostname: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=movistar
      - MYSQL_USER=telefonica
      - MYSQL_PASSWORD=vass
    ports:
      - "3306:3306"
    volumes:
      - ~/database/storage/mariadb/vass/telefonica/:/var/lib/mysql:rw
      - ~/Documentos/vass/magento.sql:/home/sql/magento.sql:rw

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"

